cam:
  build: .
  ports:
    - "81:80"
    - "3307:3306"
  environment:
     - dummy:dummy
     - http_proxy:http://proxy.pfr.co.nz:8080
     - https_proxy:http://proxy.pfr.co.nz:8080
     - no_proxy:localhost,127.0.0.1,*.pfr.co.nz,::1